name: CI

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run ESLint to check for linting issues
      - name: Run Lint
        run: npm run lint

      # Build the project to ensure there are no TypeScript or build errors
      - name: Build the app
        run: npm run build
